version: 2.1
workflows:
  semgrep:
    jobs:
      - semgrep-full-scan:
          filters:
            branches:
              only: main
          context:
            - semgrep
      - semgrep-diff-scan:
          filters:
            branches:
              ignore: main
          context:
            - semgrep
jobs:
  semgrep-full-scan:
    docker:
      - image: returntocorp/semgrep
    steps:
      - checkout
      - run:
          name: "Semgrep full scan"
          command: semgrep ci     
  semgrep-diff-scan:
    parameters:
      default_branch:
        type: string
        default: main
    docker:
      - image: returntocorp/semgrep
    steps:
      - checkout
      - run: 
          name: Semgrep diff scan
          environment: 
            SEMGREP_BASELINE_REF: << parameters.default_branch >>
          command: |
              echo -e "Current branch: $CIRCLE_BRANCH"
              export SEMGREP_BASELINE_REF=$(git merge-base $CIRCLE_BRANCH HEAD)
              echo -e "### Running a diff-aware scan against $CIRCLE_BRANCH, commit $SEMGREP_BASELINE_REF\n"
              
              # Only allow at most 1 thread and 1500MB of memory to account for the resource class
              semgrep ci --no-force-color --jobs 1 --max-memory 1500
