version: 2.1
workflows:
  semgrep:
    jobs:
      - semgrep-full-scan:
          filters:
            branches:
              only: main
          context:
            - semgrep
      - semgrep-diff-scan:
          filters:
            branches:
              ignore: main
          context:
            - semgrep
jobs:
  semgrep-full-scan:
    docker:
      - image: returntocorp/semgrep
    steps:
      - checkout
      - run:
          name: "Semgrep full scan"
          command: semgrep ci
  semgrep-diff-scan:
    parameters:
      default_branch:
        type: string
        default: main
    docker:
      - image: returntocorp/semgrep
    steps:
      - checkout
      - run: 
          name: Semgrep diff scan
          environment: 
            SEMGREP_BASELINE_REF: << parameters.default_branch >>
          command: |
            echo "Running semgrep and dumping results to JSON file"
            semgrep ci --json --output report-ssc.json || true
            json_file=report-ssc.json
            echo "Iterating through findings"
            findings=$(jq -r '.results[]' "$json_file")
            for k in $(jq '.results | keys | .[]' "$json_file"); do
                value=$(jq -r ".results[$k]" "$json_file");
                severity=$(jq -r '.extra.severity' \\<\<\< "$value");
                reachable=$(jq -r '.extra.sca_info.reachable' \\<\<\< "$value");
                if [[ $severity == "ERROR" && $reachable == "true" ]]; then
                    echo "Exiting with error code 1"
                    exit 1;
                fi
            done
            echo "There are no reachable critical-high findings"

